### ISSUE TITLE
Create or Remove Metrics at Runtime

### ISSUE THREAD

**Issue by moonheart** [prometheus-net/prometheus-net#230]
Hello devs,

Currently, I can only create metrics by `Metrics.CreateXXX` and store as static members in code.

I'm using a config center, which can refresh configs from remote.

Example remote metrics:

``` yaml
queries:
  - name: metric_a_count
    help: This is a help text
    type: counter
    query: select count(*) from table
    lables: 
      - labelA
      - labelB
```
I want to create or remove metrics when remote configs changed to take advantage of [IOptionsMonitor](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#ioptionsmonitor).

Please let me know if I'm missing something.

Thanks.
